scheduler:
  enabled: false
  escalation: 1000000
  update: 2000

media:
  allowedRoles: RSM;ZSH
  baseUrl: https://customerapproval.marutisuzuki.com
  get:
    url: https://customerapproval.marutisuzuki.com/mtab_qa/

msil:
  preprod:
    headers:
      xapikey: zkZqTRAdcx3mYvaTuwVaJy0Di8epFiTab9onDgz3
    client:
      id: 69b372e3vrtcj7pn3m6h6lq108
      secret: d49rscc860ko3umg93lbh00bfva7pa8dq39o25mnoc7lu6bgro4

app:
  version: 0.0
  build:
    number: 1
  release:
    date: "2024-01-16 15:30:00"
  mandatory: 
    update: false
  latest:
    update:
      link: https://msil-app.store/dummy-url-serviz-app/v0.0
